function quality = assessPresentationQuality(runData)
%ASSESSPRESENTATIONQUALITY Summarize saved Psychtoolbox presentation timing.
% This verifies software scheduling and recorded flip timestamps. It cannot
% prove that the physical monitor changed luminance; use a photodiode for
% that independent measurement.

quality.schemaVersion = "1.0.0";
quality.verdict = "INCOMPLETE";
quality.pass = false;
quality.completedRun = isfield(runData,'status') && ...
    isfield(runData.status,'completed') && ...
    logical(runData.status.completed);
quality.expectedFrameCount = 0;
quality.presentedFrameCount = 0;
quality.frameCountMismatchTrialCount = NaN;
quality.screenReportedMissedDeadlineCount = NaN;
quality.longFrameIntervalCount = NaN;
quality.estimatedDroppedRefreshCount = NaN;
quality.longFrameIntervalFraction = NaN;
quality.maximumMissSec = NaN;
quality.maximumFrameIntervalSec = NaN;
quality.maximumInterStimulusErrorSec = NaN;
quality.interStimulusViolationCount = NaN;
quality.interStimulusToleranceSec = NaN;
quality.maximumTrialOnsetIntervalErrorSec = NaN;
quality.trialOnsetIntervalViolationCount = NaN;
quality.trialOnsetIntervalToleranceSec = NaN;
quality.summary = "Presentation was incomplete.";

if ~isfield(runData,'display') || ...
        ~isfield(runData.display,'ifiSec') || ...
        ~isfinite(runData.display.ifiSec) || runData.display.ifiSec <= 0 || ...
        ~isfield(runData,'sequence') || ...
        ~isfield(runData.sequence,'trials') || ...
        ~isfield(runData,'presentation')
    quality.summary = ...
        "Presentation QC unavailable: required timing fields are missing.";
    return
end

ifi = double(runData.display.ifiSec);
trials = runData.sequence.trials;
presentation = runData.presentation;
nTrials = height(trials);
expectedFrames = max(1,round(double(trials.durationSec)/ifi));
presentedFrames = double(presentation.framesPresented);
quality.expectedFrameCount = sum(expectedFrames);
quality.presentedFrameCount = sum(presentedFrames);
quality.frameCountMismatchTrialCount = ...
    sum(presentedFrames ~= expectedFrames);

quality.screenReportedMissedDeadlineCount = ...
    sum(double(presentation.missedFlipCount));
quality.longFrameIntervalCount = ...
    sum(double(presentation.longFrameIntervalCount));
quality.estimatedDroppedRefreshCount = ...
    sum(double(presentation.estimatedDroppedRefreshCount));
quality.longFrameIntervalFraction = quality.longFrameIntervalCount / ...
    max(1,quality.presentedFrameCount);
quality.maximumMissSec = max(double(presentation.maximumMissSec), ...
    [],'omitnan');
quality.maximumFrameIntervalSec = ...
    max(double(presentation.maximumFrameIntervalSec),[],'omitnan');

requestedIsi = double(trials.interStimulusSec);
actualIsi = double(presentation.actualInterStimulusSec);
isiRows = (1:nTrials)' < nTrials & requestedIsi > 0 & ...
    isfinite(actualIsi);
quality.interStimulusToleranceSec = max(2*ifi,0.005);
if any(isiRows)
    isiError = actualIsi(isiRows) - requestedIsi(isiRows);
    quality.maximumInterStimulusErrorSec = max(abs(isiError));
    quality.interStimulusViolationCount = sum(abs(isiError) > ...
        quality.interStimulusToleranceSec);
else
    quality.maximumInterStimulusErrorSec = 0;
    quality.interStimulusViolationCount = 0;
end

% Frame intervals stored within a trial do not span the transition to the
% next trial. Check consecutive visual onsets separately so a pause between
% two nominally gapless stimuli cannot be missed by post-run QC.
quality.trialOnsetIntervalToleranceSec = max(2*ifi,0.005);
if istable(presentation)
    hasFlipOnsets = ismember( ...
        'flipOnsetSec',presentation.Properties.VariableNames);
else
    hasFlipOnsets = isstruct(presentation) && ...
        isfield(presentation,'flipOnsetSec');
end
if nTrials < 2
    quality.maximumTrialOnsetIntervalErrorSec = 0;
    quality.trialOnsetIntervalViolationCount = 0;
elseif hasFlipOnsets
    actualOnsetIntervals = diff(double(presentation.flipOnsetSec));
    expectedOnsetIntervals = double(trials.durationSec(1:end-1)) + ...
        double(trials.interStimulusSec(1:end-1));
    onsetErrors = actualOnsetIntervals - expectedOnsetIntervals;
    finiteRows = isfinite(onsetErrors);
    if any(finiteRows)
        quality.maximumTrialOnsetIntervalErrorSec = ...
            max(abs(onsetErrors(finiteRows)));
    end
    quality.trialOnsetIntervalViolationCount = ...
        sum(~finiteRows) + sum(abs(onsetErrors(finiteRows)) > ...
        quality.trialOnsetIntervalToleranceSec);
end

onsetIntervalsPass = ...
    isnan(quality.trialOnsetIntervalViolationCount) || ...
    quality.trialOnsetIntervalViolationCount == 0;
quality.pass = quality.completedRun && ...
    quality.frameCountMismatchTrialCount == 0 && ...
    quality.screenReportedMissedDeadlineCount == 0 && ...
    quality.longFrameIntervalCount == 0 && ...
    quality.estimatedDroppedRefreshCount == 0 && ...
    quality.interStimulusViolationCount == 0 && onsetIntervalsPass;
if quality.pass
    quality.verdict = "PASS";
    quality.summary = sprintf( ...
        'Presentation QC PASS: %d frames, no detected dropped refreshes or timing violations.', ...
        quality.presentedFrameCount);
elseif quality.completedRun
    quality.verdict = "WARN";
    quality.summary = sprintf( ...
        ['Presentation QC WARN: %d frame-count mismatch trial(s), %d ' ...
         'missed deadline(s), %d long interval(s), approximately %d ' ...
         'dropped refresh(es), %d ISI violation(s), and %d trial-onset ' ...
         'interval violation(s).'], ...
        quality.frameCountMismatchTrialCount, ...
        quality.screenReportedMissedDeadlineCount, ...
        quality.longFrameIntervalCount, ...
        quality.estimatedDroppedRefreshCount, ...
        quality.interStimulusViolationCount, ...
        quality.trialOnsetIntervalViolationCount);
end
end
