function previewSequence(ax, cfg, sequence)
%PREVIEWSEQUENCE Show the monitor, selected target, and stimulus locations.

cla(ax);
hold(ax, 'on');
displayAz = cfg.display.azimuthLimitsDeg;
displayEl = cfg.display.elevationLimitsDeg;
rectangle(ax, 'Position', [displayAz(1), displayEl(1), ...
    diff(displayAz), diff(displayEl)], 'FaceColor', [0.5 0.5 0.5], ...
    'FaceAlpha', 0.12, ...
    'EdgeColor', [0.2 0.2 0.2], 'LineWidth', 1.5);

switch string(cfg.protocol)
    case "Moving bars"
        [az, el] = vstim.mappingLimits(cfg);
        plot(ax, mean(az), mean(el), '+', 'Color', [0.1 0.35 0.8], ...
            'MarkerSize', 12, 'LineWidth', 2);
        detail = 'Bars sweep across and are clipped to the red target';

    case "Flashed bars"
        vertical = sequence.verticalPositionsDeg;
        horizontal = sequence.horizontalPositionsDeg;
        [az, el] = vstim.mappingLimits(cfg);
        scatter(ax, vertical, repmat(mean(el), size(vertical)), 32, ...
            [0.1 0.35 0.8], 'filled');
        scatter(ax, repmat(mean(az), size(horizontal)), horizontal, 32, ...
            [0.85 0.5 0.1], 'filled');
        detail = sprintf('%d vertical + %d horizontal bar positions', ...
            numel(vertical), numel(horizontal));

    case "Sparse noise"
        scatter(ax, sequence.grid.azimuthDeg, sequence.grid.elevationDeg, ...
            26, [0.1 0.35 0.8], 'filled');
        detail = sprintf('%d x %d grid = %d tile locations', ...
            sequence.effectiveGridSize(1), sequence.effectiveGridSize(2), ...
            height(sequence.grid));

    case "Fast Gabor tiling"
        scatter(ax, sequence.grid.azimuthDeg, sequence.grid.elevationDeg, ...
            30, [0.1 0.35 0.8], 'filled');
        detail = sprintf('%d x %d grid = %d grating locations', ...
            numel(sequence.azimuthAxisDeg), ...
            numel(sequence.elevationAxisDeg), height(sequence.grid));

    case "Targeted Gabor grid"
        scatter(ax, sequence.grid.azimuthDeg, sequence.grid.elevationDeg, ...
            38, [0.65 0.15 0.75], 'filled');
        side = 2*sequence.gridRadius+1;
        detail = sprintf('%d x %d targeted degree grid = %d locations', ...
            side, side, height(sequence.grid));

    case "Gabor + inverse stimuli"
        scatter(ax, sequence.centerAzimuthDeg, sequence.centerElevationDeg, ...
            65, [0.8 0.15 0.2], 'filled');
        center = [sequence.centerAzimuthDeg sequence.centerElevationDeg];
        gaborDiameter = cfg.stimulus.diameterDeg;
        inverseDiameter = cfg.stimulus.inverseDiameterDeg;
        inverseSupportDiameter = inverseDiameter + ...
            2*cfg.stimulus.edgeBlurDeg;
        rectangle(ax,'Position',[center-[gaborDiameter gaborDiameter]/2, ...
            gaborDiameter gaborDiameter],'Curvature',[1 1], ...
            'EdgeColor',[0.1 0.35 0.85],'LineWidth',2);
        rectangle(ax,'Position',[center-[inverseDiameter inverseDiameter]/2, ...
            inverseDiameter inverseDiameter],'Curvature',[1 1], ...
            'EdgeColor',[0.85 0.2 0.2],'LineWidth',2,'LineStyle','--');
        rectangle(ax,'Position',[center-[inverseSupportDiameter ...
            inverseSupportDiameter]/2,inverseSupportDiameter ...
            inverseSupportDiameter],'Curvature',[1 1], ...
            'EdgeColor',[0.85 0.45 0.45],'LineWidth',1,'LineStyle',':');
        detail = sprintf( ...
            ['%d orientations; Gabor %.1f deg (blue), inverse solid core ' ...
            '%.1f deg (red dashed)'], ...
            numel(unique(sequence.trials.orientationDeg)), ...
            gaborDiameter,inverseDiameter);
end

axis(ax, 'equal');
xlim(ax, displayAz + [-1 1]*max(1, 0.03*diff(displayAz)));
ylim(ax, displayEl + [-1 1]*max(1, 0.03*diff(displayEl)));
xlabel(ax, 'Azimuth (deg)');
ylabel(ax, 'Elevation (deg)');
title(ax, {'Monitor and target region'; detail});
grid(ax, 'on');
hold(ax, 'off');
end
